apiVersion: v1
kind: Secret
metadata:
    name: mysqlcreds
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:OCnQ2A==,iv:HN2nIt1jI79ZHt1CXLW7aHYvRcas7/xOwa4cvwpGbq8=,tag:OrDfDOBqqCAzabmqjLWxcQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:uXajBbs=,iv:qkKaLuzQrMOXxOASDreL3TP4YlQK+mNlY0EJXnbGJuA=,tag:732al7BDw/vVQ3khdiFVMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-30T19:34:12Z"
    mac: ENC[AES256_GCM,data:CD/Lxz4QYkMBUkifb4mSVvMQHw+CYsYl5Jvff6dx3NBnrq3CzpWaKsYAc/PypkvxoNQGn25N86mS5y7DqBvbwatlCbUCKPGvCigCImY2XDRovtCQXB6H8oM3kNSU82g0s8CVw2Kko0sdXGRoYwm4pMt82h/omWvutBIwIMSvDJI=,iv:IC95FTREz5ojsFNERNASfNsyWNdi8r2bD1nHfMEeOzc=,tag:zUKqBAlo26GiDdY4YP0EVA==,type:str]
    pgp:
        - created_at: "2023-03-30T19:31:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA7JOfqvj9C64AQgAtbZ0cPhL5Jfy/1wWj7nPF2dAMi1UQ5aGftqiWFkbLN89
            MPwdJpxM32ff5ZrFwBvXVFugKV3mx0HCEobAH/xaoNkDxSXuBz2ljYywFbUNlWx6
            PvxWrYPxKJYealbz1Kr97s5UrsGOppHIbsh3eYq//8HpKB6dSUO3FIWMi+58RKLc
            ZaHiC2Sr9LZmZPg7UA+U8OfkDKTX8olfCjYZ15AViNuo8eafpHdj331NIX6a6ZTp
            dyFnXvi5YJq1mghztIxP8f7nV10XgqNTIIY7dQYE6Hi54h5ZH4ikkMyUEHhw24Xa
            btmovO8BWbsK4tWtG21ew1x4+axCvzjKA5rTAtcWQ9JeAU3VDgfp4VZWC8SepMWB
            37oQ592Kcc7g6TmSFG/0IW8KPLJd0eN9H6Gwsyz9F4V15ppiE/qWBx+8ZOWYvX3T
            5lwaS49J4evvsHugxsE47lNPLhadAa6ivpxuFlYwJg==
            =NGZG
            -----END PGP MESSAGE-----
          fp: 30A62A1166CBCD93E2400B2B7217920F5996FC1B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
